name: media_kit_libs_android_video
description: ReKazumi Android media-kit runtime with fixed 3x Adreno AFME support.
version: 1.3.6+rekazumi.2
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmercerind.media_kit_libs_android_video
        pluginClass: MediaKitLibsAndroidVideoPlugin
